### ISSUE TITLE
Apache2 Restart crashes with Error in Apache Config

### ISSUE THREAD

**Issue by janspeller** [Derroylo/gitpod-tool#54]
GITPOD_REPO_ROOT doesn't exist in Snapshots so Apache Config has an invalid ContentRoot

**Comment by janspeller** [comment]
@Derroylo FYI

**Comment by Derroylo** [comment]
Related gitpod issue: https://github.com/gitpod-io/gitpod/issues/9804
Setting the variable in the file gpt.sh which should fix this issue till it will be finally fixed by the gitpod team.

Closing this issue. Thanks @janspeller
